# Dockerfile.liquibase
FROM liquibase/liquibase:latest

USER root

# Install PostgreSQL client
RUN apt-get update && \
    apt-get install -y postgresql-client && \
    rm -rf /var/lib/apt/lists/*

USER liquibase
